name: DockerHub Ci

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build-and-Push:
    runs-on: ubuntu-latest

    steps:
    #Checkout the repository
      - name: Checkout Repository 
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "date=$(date + "%Y-%m-%d")" >> $GITHUB_ENV

      - name: Print date var
        run: |
          echo "Print current date ${{env.date}}"
          date
          date +"%Y-%m-%d %H:%M:%S"
        