name: DockerHub Ci

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build-and-Push:
    runs-on: ubuntu-latest

    steps:
    #Checkout the repository
      - name: Checkout Repository 
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: |
          echo "date_today=$(date + "%Y-%m-%d")" >> $GITHUB_ENV
          echo "::set-output name=current_date::$(date +'%Y-%m-%d')"

      - name: Print date var
        run: |
          echo "Print current date $date_today"
          date
          date +"%Y-%m-%d %H:%M:%S"
          echo "print ${{steps.date.outputs.current_date}}"
        